In [1]:
import pandas as pd

In [13]:
data = pd.Series([2,3,44,6,7,9,22],name='Marks', index=["A","B","C","D","E","F","G"])

In [14]:
data

A     2
B     3
C    44
D     6
E     7
F     9
G    22
Name: Marks, dtype: int64

In [25]:
df = pd.DataFrame([["Yasir", 27, "M"],
                   ["Fatima", 30, "F"],
                   ["ALI", 27, "M"]], columns=["Name","Age","Gender"], index=["std1","std2","std3"])

In [26]:
df

        Name  Age Gender
std1   Yasir   27      M
std2  Fatima   30      F
std3     ALI   27      M

In [27]:
df['Name']

std1     Yasir
std2    Fatima
std3       ALI
Name: Name, dtype: str

In [28]:
df.Name

std1     Yasir
std2    Fatima
std3       ALI
Name: Name, dtype: str

In [30]:
df[['Name','Age']]

        Name  Age
std1   Yasir   27
std2  Fatima   30
std3     ALI   27

In [32]:
df.loc["std1"]

Name      Yasir
Age          27
Gender        M
Name: std1, dtype: object

In [51]:
data = [{"Name":'Yasir1',"Scince":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90},
        {"Name":'Yasir2',"Scince":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90},
        {"Name":'Yasir3',"Scince":None,"Math":50,"Urdu":60,"English":70,"Sindhi":90},
        {"Name":'Yasir4',"Scince":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90}
       ]
df = pd.DataFrame(data, index = ["std1","std2","std3","std4"])

In [52]:
df

        Name  Scince  Math  Urdu  English  Sindhi
std1  Yasir1    40.0    50    60       70      90
std2  Yasir2    40.0    50    60       70      90
std3  Yasir3     NaN    50    60       70      90
std4  Yasir4    40.0    50    60       70      90

In [53]:
df[["Name","Scince"]]

        Name  Scince
std1  Yasir1    40.0
std2  Yasir2    40.0
std3  Yasir3     NaN
std4  Yasir4    40.0

In [54]:
df[["Name","Scince"]].loc[["std1","std2"]]

        Name  Scince
std1  Yasir1    40.0
std2  Yasir2    40.0

In [55]:
df.iloc[:,::2]

        Name  Math  English
std1  Yasir1    50       70
std2  Yasir2    50       70
std3  Yasir3    50       70
std4  Yasir4    50       70

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, std1 to std4
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      str
 1   Scince   3 non-null      float64
 2   Math     4 non-null      int64
 3   Urdu     4 non-null      int64
 4   English  4 non-null      int64
 5   Sindhi   4 non-null      int64
dtypes: float64(1), int64(4), str(1)
memory usage: 396.0+ bytes

In [58]:
df = df.astype({"English":str})

In [59]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, std1 to std4
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      str
 1   Scince   3 non-null      float64
 2   Math     4 non-null      int64
 3   Urdu     4 non-null      int64
 4   English  4 non-null      str
 5   Sindhi   4 non-null      int64
dtypes: float64(1), int64(3), str(2)
memory usage: 396.0+ bytes

In [105]:
student_data = pd.read_csv("student.csv", na_values=["abcent"])

In [69]:
student_data.head(6)

   English  Urdu  Sindhi  Science  Math
0       50    70      90       80    85
1       55    72      60       70    75
2       80    50      90       83    65
3       50    60      80       87    65
4       53    40      83       70    95
5       50    62      87       80    45

In [65]:
student_data.tail(6)

   English  Urdu  Sindhi  Science  Math
4       53    40      83       70    95
5       50    62      87       80    45
6       40    73      60       70    55
7       59    75      60       30    65
8       68    60      80       30    75
9       58    70      50       80    65

In [70]:
student_data.columns

Index(['English', 'Urdu', 'Sindhi', 'Science', 'Math'], dtype='str')

In [71]:
student_data.index

RangeIndex(start=0, stop=10, step=1)

In [72]:
student_data.describe()

         English       Urdu     Sindhi    Science       Math
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   56.300000  63.200000  74.000000  68.000000  69.000000
std    11.086027  11.252654  14.899664  20.864643  14.298407
min    40.000000  40.000000  50.000000  30.000000  45.000000
25%    50.000000  60.000000  60.000000  70.000000  65.000000
50%    54.000000  66.000000  80.000000  75.000000  65.000000
75%    58.750000  71.500000  86.000000  80.000000  75.000000
max    80.000000  75.000000  90.000000  87.000000  95.000000

In [76]:
student_data.isna().sum()

English    0
Urdu       1
Sindhi     0
Science    1
Math       1
dtype: int64

In [77]:
student_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   English  10 non-null     int64
 1   Urdu     9 non-null      float64
 2   Sindhi   10 non-null     int64
 3   Science  9 non-null      float64
 4   Math     9 non-null      float64
dtypes: float64(3), int64(2)
memory usage: 532.0 bytes

In [78]:
student_data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [80]:
student_data.sum(axis=1)

0    290.0
1    332.0
2    368.0
3    342.0
4    271.0
5    324.0
6    298.0
7    214.0
8    313.0
9    323.0
dtype: float64

In [81]:
student_data.mean()

English    56.300000
Urdu       61.888889
Sindhi     74.000000
Science    67.777778
Math       67.222222
dtype: float64

In [85]:
subject_max = student_data.idxmax()

In [86]:
subject_max.values

array([2, 6, 0, 3, 4])

In [87]:
subject_max.index

Index(['English', 'Urdu', 'Sindhi', 'Science', 'Math'], dtype='str')

In [88]:
student_data

   English  Urdu  Sindhi  Science  Math
0       50  70.0      90     80.0   NaN
1       55  72.0      60     70.0  75.0
2       80  50.0      90     83.0  65.0
3       50  60.0      80     87.0  65.0
4       53  40.0      83      NaN  95.0
5       50  62.0      87     80.0  45.0
6       40  73.0      60     70.0  55.0
7       59   NaN      60     30.0  65.0
8       68  60.0      80     30.0  75.0
9       58  70.0      50     80.0  65.0

In [90]:
student_data["obtain"] = student_data.sum(axis=1)

In [91]:
student_data

   English  Urdu  Sindhi  Science  Math  obtain
0       50  70.0      90     80.0   NaN   290.0
1       55  72.0      60     70.0  75.0   332.0
2       80  50.0      90     83.0  65.0   368.0
3       50  60.0      80     87.0  65.0   342.0
4       53  40.0      83      NaN  95.0   271.0
5       50  62.0      87     80.0  45.0   324.0
6       40  73.0      60     70.0  55.0   298.0
7       59   NaN      60     30.0  65.0   214.0
8       68  60.0      80     30.0  75.0   313.0
9       58  70.0      50     80.0  65.0   323.0

In [95]:
student_data['Total'] = 500

In [96]:
student_data

   English  Urdu  Sindhi  Science  Math  obtain  Total
0       50  70.0      90     80.0   NaN   290.0    500
1       55  72.0      60     70.0  75.0   332.0    500
2       80  50.0      90     83.0  65.0   368.0    500
3       50  60.0      80     87.0  65.0   342.0    500
4       53  40.0      83      NaN  95.0   271.0    500
5       50  62.0      87     80.0  45.0   324.0    500
6       40  73.0      60     70.0  55.0   298.0    500
7       59   NaN      60     30.0  65.0   214.0    500
8       68  60.0      80     30.0  75.0   313.0    500
9       58  70.0      50     80.0  65.0   323.0    500

In [98]:
student_data["Per"] = (student_data.obtain / student_data.Total)*100

In [99]:
student_data

   English  Urdu  Sindhi  Science  Math  obtain  Total   Per
0       50  70.0      90     80.0   NaN   290.0    500  58.0
1       55  72.0      60     70.0  75.0   332.0    500  66.4
2       80  50.0      90     83.0  65.0   368.0    500  73.6
3       50  60.0      80     87.0  65.0   342.0    500  68.4
4       53  40.0      83      NaN  95.0   271.0    500  54.2
5       50  62.0      87     80.0  45.0   324.0    500  64.8
6       40  73.0      60     70.0  55.0   298.0    500  59.6
7       59   NaN      60     30.0  65.0   214.0    500  42.8
8       68  60.0      80     30.0  75.0   313.0    500  62.6
9       58  70.0      50     80.0  65.0   323.0    500  64.6

In [104]:
student_data.Per.sort_values()

7    42.8
4    54.2
0    58.0
6    59.6
8    62.6
9    64.6
5    64.8
1    66.4
3    68.4
2    73.6
Name: Per, dtype: float64

In [106]:
std_data = pd.read_csv("student_marks.csv",na_values=["abcent"])

In [107]:
std_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   roll_no     500 non-null    str
 1   name        500 non-null    str
 2   quiz_1      450 non-null    float64
 3   quiz_2      450 non-null    float64
 4   quiz_3      451 non-null    float64
 5   final_exam  450 non-null    float64
dtypes: float64(4), str(2)
memory usage: 23.6 KB

In [108]:
std_data["obtain"] = std_data.iloc[:,2:].sum(axis = 1)

In [109]:
std_data

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0
3,SMIT/DSAI/004,Thomas Ortiz,7.0,-2.0,5.0,19.0,29.0
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0
...,...,...,...,...,...,...,...
495,SMIT/DSAI/496,Rita Torres,9.0,9.0,7.0,NaN,25.0
496,SMIT/DSAI/497,Paul Thomas,7.0,8.0,7.0,NaN,22.0
497,SMIT/DSAI/498,Jacob Simon,9.0,1.0,10.0,10.0,30.0
498,SMIT/DSAI/499,Kimberly Ayers,9.0,7.0,1.0,3.0,20.0
499,SMIT/DSAI/500,Alvin Brown,9.0,7.0,8.0,NaN,24.0

In [110]:
std_data["total"] = 100

In [111]:
std_data['per'] = (std_data.obtain / std_data.total)*100

In [112]:
std_data

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain,total,per
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0,100,19.0
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0,100,15.0
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0,100,27.0
3,SMIT/DSAI/004,Thomas Ortiz,7.0,-2.0,5.0,19.0,29.0,100,29.0
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0,100,35.0
...,...,...,...,...,...,...,...,...,...
495,SMIT/DSAI/496,Rita Torres,9.0,9.0,7.0,NaN,25.0,100,25.0
496,SMIT/DSAI/497,Paul Thomas,7.0,8.0,7.0,NaN,22.0,100,22.0
497,SMIT/DSAI/498,Jacob Simon,9.0,1.0,10.0,10.0,30.0,100,30.0
498,SMIT/DSAI/499,Kimberly Ayers,9.0,7.0,1.0,3.0,20.0,100,20.0
499,SMIT/DSAI/500,Alvin Brown,9.0,7.0,8.0,NaN,24.0,100,24.0

In [113]:
std_data["rank"] = std_data.per.sort_values().index+1

In [114]:
std_data

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain,total,per,rank
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0,100,19.0,24
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0,100,15.0,140
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0,100,27.0,193
3,SMIT/DSAI/004,Thomas Ortiz,7.0,-2.0,5.0,19.0,29.0,100,29.0,200
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0,100,35.0,180
...,...,...,...,...,...,...,...,...,...,...
495,SMIT/DSAI/496,Rita Torres,9.0,9.0,7.0,NaN,25.0,100,25.0,289
496,SMIT/DSAI/497,Paul Thomas,7.0,8.0,7.0,NaN,22.0,100,22.0,275
497,SMIT/DSAI/498,Jacob Simon,9.0,1.0,10.0,10.0,30.0,100,30.0,278
498,SMIT/DSAI/499,Kimberly Ayers,9.0,7.0,1.0,3.0,20.0,100,20.0,409
499,SMIT/DSAI/500,Alvin Brown,9.0,7.0,8.0,NaN,24.0,100,24.0,358