In [1]:
import pandas as pd

In [2]:
data = pd.Series([2,3,44,6,7,9,22],name='Marks', index=["A","B","C","D","E","F","G"])

In [3]:
data

A     2
B     3
C    44
D     6
E     7
F     9
G    22
Name: Marks, dtype: int64

In [4]:
df = pd.DataFrame([["Yasir", 27, "M"],
                   ["Fatima", 30, "F"],
                   ["ALI", 27, "M"]], columns=["Name","Age","Gender"], index=["std1","std2","std3"])

In [5]:
df

        Name  Age Gender
std1   Yasir   27      M
std2  Fatima   30      F
std3     ALI   27      M

In [6]:
df['Name']

std1     Yasir
std2    Fatima
std3       ALI
Name: Name, dtype: str

In [7]:
df.Name

std1     Yasir
std2    Fatima
std3       ALI
Name: Name, dtype: str

In [8]:
df[['Name','Age']]

        Name  Age
std1   Yasir   27
std2  Fatima   30
std3     ALI   27

In [9]:
df.loc["std1"]

Name      Yasir
Age          27
Gender        M
Name: std1, dtype: object

In [10]:
data = [{"Name":'Yasir1',"Scince":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90},
        {"Name":'Yasir2',"Scince":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90},
        {"Name":'Yasir3',"Scince":None,"Math":50,"Urdu":60,"English":70,"Sindhi":90},
        {"Name":'Yasir4',"Scince":40,"Math":50,"Urdu":60,"English":70,"Sindhi":90}
       ]
df = pd.DataFrame(data, index = ["std1","std2","std3","std4"])

In [11]:
df

        Name  Scince  Math  Urdu  English  Sindhi
std1  Yasir1    40.0    50    60       70      90
std2  Yasir2    40.0    50    60       70      90
std3  Yasir3     NaN    50    60       70      90
std4  Yasir4    40.0    50    60       70      90

In [12]:
df[["Name","Scince"]]

        Name  Scince
std1  Yasir1    40.0
std2  Yasir2    40.0
std3  Yasir3     NaN
std4  Yasir4    40.0

In [13]:
df[["Name","Scince"]].loc[["std1","std2"]]

        Name  Scince
std1  Yasir1    40.0
std2  Yasir2    40.0

In [14]:
df.iloc[:,::2]

        Name  Math  English
std1  Yasir1    50       70
std2  Yasir2    50       70
std3  Yasir3    50       70
std4  Yasir4    50       70

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, std1 to std4
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      str
 1   Scince   3 non-null      float64
 2   Math     4 non-null      int64
 3   Urdu     4 non-null      int64
 4   English  4 non-null      int64
 5   Sindhi   4 non-null      int64
dtypes: float64(1), int64(4), str(1)
memory usage: 396.0+ bytes

In [16]:
df = df.astype({"English":str})

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, std1 to std4
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      str
 1   Scince   3 non-null      float64
 2   Math     4 non-null      int64
 3   Urdu     4 non-null      int64
 4   English  4 non-null      str
 5   Sindhi   4 non-null      int64
dtypes: float64(1), int64(3), str(2)
memory usage: 396.0+ bytes

In [18]:
student_data = pd.read_csv("student.csv", na_values=["abcent"])

In [19]:
student_data.head(6)

   English  Urdu  Sindhi  Science  Math
0       50  70.0      90     80.0   NaN
1       55  72.0      60     70.0  75.0
2       80  50.0      90     83.0  65.0
3       50  60.0      80     87.0  65.0
4       53  40.0      83      NaN  95.0
5       50  62.0      87     80.0  45.0

In [20]:
student_data.tail(6)

   English  Urdu  Sindhi  Science  Math
4       53  40.0      83      NaN  95.0
5       50  62.0      87     80.0  45.0
6       40  73.0      60     70.0  55.0
7       59   NaN      60     30.0  65.0
8       68  60.0      80     30.0  75.0
9       58  70.0      50     80.0  65.0

In [21]:
student_data.columns

Index(['English', 'Urdu', 'Sindhi', 'Science', 'Math'], dtype='str')

In [22]:
student_data.index

RangeIndex(start=0, stop=10, step=1)

In [23]:
student_data.describe()

         English       Urdu     Sindhi    Science       Math
count  10.000000   9.000000  10.000000   9.000000   9.000000
mean   56.300000  61.888889  74.000000  67.777778  67.222222
std    11.086027  11.095545  14.899664  22.117740  13.944334
min    40.000000  40.000000  50.000000  30.000000  45.000000
25%    50.000000  60.000000  60.000000  70.000000  65.000000
50%    54.000000  62.000000  80.000000  80.000000  65.000000
75%    58.750000  70.000000  86.000000  80.000000  75.000000
max    80.000000  73.000000  90.000000  87.000000  95.000000

In [24]:
student_data.isna().sum()

English    0
Urdu       1
Sindhi     0
Science    1
Math       1
dtype: int64

In [25]:
student_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   English  10 non-null     int64
 1   Urdu     9 non-null      float64
 2   Sindhi   10 non-null     int64
 3   Science  9 non-null      float64
 4   Math     9 non-null      float64
dtypes: float64(3), int64(2)
memory usage: 532.0 bytes

In [26]:
student_data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [27]:
student_data.sum(axis=1)

0    290.0
1    332.0
2    368.0
3    342.0
4    271.0
5    324.0
6    298.0
7    214.0
8    313.0
9    323.0
dtype: float64

In [28]:
student_data.mean()

English    56.300000
Urdu       61.888889
Sindhi     74.000000
Science    67.777778
Math       67.222222
dtype: float64

In [29]:
subject_max = student_data.idxmax()

In [30]:
subject_max.values

array([2, 6, 0, 3, 4])

In [31]:
subject_max.index

Index(['English', 'Urdu', 'Sindhi', 'Science', 'Math'], dtype='str')

In [32]:
student_data

   English  Urdu  Sindhi  Science  Math
0       50  70.0      90     80.0   NaN
1       55  72.0      60     70.0  75.0
2       80  50.0      90     83.0  65.0
3       50  60.0      80     87.0  65.0
4       53  40.0      83      NaN  95.0
5       50  62.0      87     80.0  45.0
6       40  73.0      60     70.0  55.0
7       59   NaN      60     30.0  65.0
8       68  60.0      80     30.0  75.0
9       58  70.0      50     80.0  65.0

In [33]:
student_data["obtain"] = student_data.sum(axis=1)

In [34]:
student_data

   English  Urdu  Sindhi  Science  Math  obtain
0       50  70.0      90     80.0   NaN   290.0
1       55  72.0      60     70.0  75.0   332.0
2       80  50.0      90     83.0  65.0   368.0
3       50  60.0      80     87.0  65.0   342.0
4       53  40.0      83      NaN  95.0   271.0
5       50  62.0      87     80.0  45.0   324.0
6       40  73.0      60     70.0  55.0   298.0
7       59   NaN      60     30.0  65.0   214.0
8       68  60.0      80     30.0  75.0   313.0
9       58  70.0      50     80.0  65.0   323.0

In [35]:
student_data['Total'] = 500

In [36]:
student_data

   English  Urdu  Sindhi  Science  Math  obtain  Total
0       50  70.0      90     80.0   NaN   290.0    500
1       55  72.0      60     70.0  75.0   332.0    500
2       80  50.0      90     83.0  65.0   368.0    500
3       50  60.0      80     87.0  65.0   342.0    500
4       53  40.0      83      NaN  95.0   271.0    500
5       50  62.0      87     80.0  45.0   324.0    500
6       40  73.0      60     70.0  55.0   298.0    500
7       59   NaN      60     30.0  65.0   214.0    500
8       68  60.0      80     30.0  75.0   313.0    500
9       58  70.0      50     80.0  65.0   323.0    500

In [37]:
student_data["Per"] = (student_data.obtain / student_data.Total)*100

In [38]:
student_data

   English  Urdu  Sindhi  Science  Math  obtain  Total   Per
0       50  70.0      90     80.0   NaN   290.0    500  58.0
1       55  72.0      60     70.0  75.0   332.0    500  66.4
2       80  50.0      90     83.0  65.0   368.0    500  73.6
3       50  60.0      80     87.0  65.0   342.0    500  68.4
4       53  40.0      83      NaN  95.0   271.0    500  54.2
5       50  62.0      87     80.0  45.0   324.0    500  64.8
6       40  73.0      60     70.0  55.0   298.0    500  59.6
7       59   NaN      60     30.0  65.0   214.0    500  42.8
8       68  60.0      80     30.0  75.0   313.0    500  62.6
9       58  70.0      50     80.0  65.0   323.0    500  64.6

In [39]:
student_data.Per.sort_values()

7    42.8
4    54.2
0    58.0
6    59.6
8    62.6
9    64.6
5    64.8
1    66.4
3    68.4
2    73.6
Name: Per, dtype: float64

In [40]:
std_data = pd.read_csv("student_marks.csv",na_values=["abcent"])

In [41]:
std_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   roll_no     500 non-null    str
 1   name        500 non-null    str
 2   quiz_1      450 non-null    float64
 3   quiz_2      450 non-null    float64
 4   quiz_3      451 non-null    float64
 5   final_exam  450 non-null    float64
dtypes: float64(4), str(2)
memory usage: 23.6 KB

In [42]:
std_data["obtain"] = std_data.iloc[:,2:].sum(axis = 1)

In [43]:
std_data

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0
3,SMIT/DSAI/004,Thomas Ortiz,7.0,-2.0,5.0,19.0,29.0
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0
...,...,...,...,...,...,...,...
495,SMIT/DSAI/496,Rita Torres,9.0,9.0,7.0,NaN,25.0
496,SMIT/DSAI/497,Paul Thomas,7.0,8.0,7.0,NaN,22.0
497,SMIT/DSAI/498,Jacob Simon,9.0,1.0,10.0,10.0,30.0
498,SMIT/DSAI/499,Kimberly Ayers,9.0,7.0,1.0,3.0,20.0
499,SMIT/DSAI/500,Alvin Brown,9.0,7.0,8.0,NaN,24.0

In [44]:
std_data["total"] = 100

In [45]:
std_data['per'] = (std_data.obtain / std_data.total)*100

In [46]:
std_data

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain,total,per
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0,100,19.0
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0,100,15.0
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0,100,27.0
3,SMIT/DSAI/004,Thomas Ortiz,7.0,-2.0,5.0,19.0,29.0,100,29.0
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0,100,35.0
...,...,...,...,...,...,...,...,...,...
495,SMIT/DSAI/496,Rita Torres,9.0,9.0,7.0,NaN,25.0,100,25.0
496,SMIT/DSAI/497,Paul Thomas,7.0,8.0,7.0,NaN,22.0,100,22.0
497,SMIT/DSAI/498,Jacob Simon,9.0,1.0,10.0,10.0,30.0,100,30.0
498,SMIT/DSAI/499,Kimberly Ayers,9.0,7.0,1.0,3.0,20.0,100,20.0
499,SMIT/DSAI/500,Alvin Brown,9.0,7.0,8.0,NaN,24.0,100,24.0

In [47]:
std_data["rank"] = std_data.per.sort_values().index+1

In [48]:
std_data

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain,total,per,rank
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0,100,19.0,24
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0,100,15.0,140
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0,100,27.0,193
3,SMIT/DSAI/004,Thomas Ortiz,7.0,-2.0,5.0,19.0,29.0,100,29.0,200
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0,100,35.0,180
...,...,...,...,...,...,...,...,...,...,...
495,SMIT/DSAI/496,Rita Torres,9.0,9.0,7.0,NaN,25.0,100,25.0,289
496,SMIT/DSAI/497,Paul Thomas,7.0,8.0,7.0,NaN,22.0,100,22.0,275
497,SMIT/DSAI/498,Jacob Simon,9.0,1.0,10.0,10.0,30.0,100,30.0,278
498,SMIT/DSAI/499,Kimberly Ayers,9.0,7.0,1.0,3.0,20.0,100,20.0,409
499,SMIT/DSAI/500,Alvin Brown,9.0,7.0,8.0,NaN,24.0,100,24.0,358

In [49]:
house = pd.read_csv('datasets/house_prices.csv')

In [50]:
house.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [51]:
house.isna().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [52]:
house.drop(['Dimensions','Plot Area','Super Area'],axis=1, inplace=True)

In [53]:
new_data = house[["Amount(in rupees)","Price (in rupees)","location","Status","Transaction","Furnishing","Bathroom","Carpet Area"]]

In [54]:
new_data.isna().sum()

Amount(in rupees)        0
Price (in rupees)    17665
location                 0
Status                 615
Transaction             83
Furnishing            2897
Bathroom               828
Carpet Area          80673
dtype: int64

In [55]:
new_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Amount(in rupees)  187531 non-null  str
 1   Price (in rupees)  169866 non-null  float64
 2   location           187531 non-null  str
 3   Status             186916 non-null  str
 4   Transaction        187448 non-null  str
 5   Furnishing         184634 non-null  str
 6   Bathroom           186703 non-null  str
 7   Carpet Area        106858 non-null  str
dtypes: float64(1), str(7)
memory usage: 11.4 MB

In [56]:
new_data[["Price (in rupees)","Bathroom"]].fillna(new_data[["Price (in rupees)","Bathroom"]].mean())

TypeError: Cannot perform reduction 'mean' with string dtype

In [57]:
data = pd.read_csv("housing_price_dataset.csv")

In [ ]:
data

In [ ]:
data.info()

In [ ]:
data.isna().sum()

In [ ]:
data.dropna(axis=0, inplace=True)

In [ ]:
data.isna().sum()

In [ ]:
data.duplicated().sum()

In [ ]:
data["price(per squarefeet"] = data.Price/data.SquareFeet

In [ ]:
group_data = data.groupby('Neighborhood')

In [ ]:
group_data.get_group("Urban")

In [ ]:
data.Neighborhood.unique()

In [ ]:
for cat in data.Neighborhood.unique():
    cat_data = group_data.get_group(cat)
    print(f"{cat}: {cat_data['price(per squarefeet'].max()}")

In [58]:
students = pd.read_csv("students_five_classes.csv")

In [59]:
students["class"] = students.roll_no.str.split('/').str[1]

In [60]:
students

           roll_no           name  exam1  exam2  final_exam class
0    SMIT/DSAI/001    David Iqbal     20     16          35  DSAI
1    SMIT/DSAI/002    Ahmed Ahmed     13      7          40  DSAI
2    SMIT/DSAI/003     John Zahid     13     24          47  DSAI
3    SMIT/DSAI/004    David Brown      0     15          24  DSAI
4    SMIT/DSAI/005    Fatima Khan     20      8           6  DSAI
..             ...            ...    ...    ...         ...   ...
495   SMIT/MAW/096     Sara Zahid      8     10          45   MAW
496   SMIT/MAW/097     Ayesha Ali     14      3          31   MAW
497   SMIT/MAW/098  Michael Brown      2     20          50   MAW
498   SMIT/MAW/099     Sara Malik     24      6          16   MAW
499   SMIT/MAW/100       Noor Ali      9     11          44   MAW

[500 rows x 6 columns]

In [61]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   roll_no     500 non-null    str
 1   name        500 non-null    str
 2   exam1       500 non-null    int64
 3   exam2       500 non-null    int64
 4   final_exam  500 non-null    int64
 5   class       500 non-null    object
dtypes: int64(3), object(1), str(2)
memory usage: 23.6+ KB

In [62]:
students['obtain'] = students.iloc[:,2:-1].sum(axis = 1)

In [63]:
students['total'] = 100

In [64]:
students['per'] = (students.obtain/students.total)*100

In [65]:
students

,roll_no,name,exam1,exam2,final_exam,class,obtain,total,per
0,SMIT/DSAI/001,David Iqbal,20,16,35,DSAI,71,100,71.0
1,SMIT/DSAI/002,Ahmed Ahmed,13,7,40,DSAI,60,100,60.0
2,SMIT/DSAI/003,John Zahid,13,24,47,DSAI,84,100,84.0
3,SMIT/DSAI/004,David Brown,0,15,24,DSAI,39,100,39.0
4,SMIT/DSAI/005,Fatima Khan,20,8,6,DSAI,34,100,34.0
...,...,...,...,...,...,...,...,...,...
495,SMIT/MAW/096,Sara Zahid,8,10,45,MAW,63,100,63.0
496,SMIT/MAW/097,Ayesha Ali,14,3,31,MAW,48,100,48.0
497,SMIT/MAW/098,Michael Brown,2,20,50,MAW,72,100,72.0
498,SMIT/MAW/099,Sara Malik,24,6,16,MAW,46,100,46.0
499,SMIT/MAW/100,Noor Ali,9,11,44,MAW,64,100,64.0

In [66]:
def grade(x):
    if x>=80:
        return 'A'
    elif x>=60:
        return 'B'
    elif x>=40:
        return 'C'
    elif x<40:
        return 'F'

In [67]:
students['grades'] = students.per.apply(grade)

In [68]:
students.to_csv("updated_student_data.csv")

In [69]:
students

,roll_no,name,exam1,exam2,final_exam,class,obtain,total,per,grades
0,SMIT/DSAI/001,David Iqbal,20,16,35,DSAI,71,100,71.0,B
1,SMIT/DSAI/002,Ahmed Ahmed,13,7,40,DSAI,60,100,60.0,B
2,SMIT/DSAI/003,John Zahid,13,24,47,DSAI,84,100,84.0,A
3,SMIT/DSAI/004,David Brown,0,15,24,DSAI,39,100,39.0,F
4,SMIT/DSAI/005,Fatima Khan,20,8,6,DSAI,34,100,34.0,F
...,...,...,...,...,...,...,...,...,...,...
495,SMIT/MAW/096,Sara Zahid,8,10,45,MAW,63,100,63.0,B
496,SMIT/MAW/097,Ayesha Ali,14,3,31,MAW,48,100,48.0,C
497,SMIT/MAW/098,Michael Brown,2,20,50,MAW,72,100,72.0,B
498,SMIT/MAW/099,Sara Malik,24,6,16,MAW,46,100,46.0,C
499,SMIT/MAW/100,Noor Ali,9,11,44,MAW,64,100,64.0,B

In [70]:
students.grades.value_counts()

grades
C    180
F    150
B    149
A     21
Name: count, dtype: int64

In [71]:
group_std = students.groupby('class')

In [72]:
group_std['grades'].value_counts()

class  grades
DM     B         33
       C         31
       F         30
       A          6
DSAI   C         35
       B         30
       F         30
       A          5
GD     C         34
       B         33
       F         30
       A          3
MAW    C         45
       F         27
       B         26
       A          2
UIUX   C         35
       F         33
       B         27
       A          5
Name: count, dtype: int64

In [73]:
group_std.get_group('DM').sort_values(by='per',ascending = False).head(3)

,roll_no,name,exam1,exam2,final_exam,class,obtain,total,per,grades
108,SMIT/DM/009,Sara Iqbal,19,17,49,DM,85,100,85.0,A
184,SMIT/DM/085,David Malik,10,25,50,DM,85,100,85.0,A
146,SMIT/DM/047,David Ahmed,17,23,43,DM,83,100,83.0,A

In [79]:
group_std.get_group('DM').grades.value_counts()[['A','B','C']].sum()/100

np.float64(0.7)

In [94]:
students

,roll_no,name,exam1,exam2,final_exam,class,obtain,total,per,grades
0,SMIT/DSAI/001,David Iqbal,20,16,35,DSAI,71,100,71.0,B
1,SMIT/DSAI/002,Ahmed Ahmed,13,7,40,DSAI,60,100,60.0,B
2,SMIT/DSAI/003,John Zahid,13,24,47,DSAI,84,100,84.0,A
3,SMIT/DSAI/004,David Brown,0,15,24,DSAI,39,100,39.0,F
4,SMIT/DSAI/005,Fatima Khan,20,8,6,DSAI,34,100,34.0,F
...,...,...,...,...,...,...,...,...,...,...
495,SMIT/MAW/096,Sara Zahid,8,10,45,MAW,63,100,63.0,B
496,SMIT/MAW/097,Ayesha Ali,14,3,31,MAW,48,100,48.0,C
497,SMIT/MAW/098,Michael Brown,2,20,50,MAW,72,100,72.0,B
498,SMIT/MAW/099,Sara Malik,24,6,16,MAW,46,100,46.0,C
499,SMIT/MAW/100,Noor Ali,9,11,44,MAW,64,100,64.0,B

In [95]:
orders = pd.read_csv('orders.csv')

In [97]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 2584 entries, 0 to 2583
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     2584 non-null   str
 1   customer_id  2584 non-null   str
 2   product_id   2584 non-null   str
 3   quantity     2584 non-null   int64
 4   order_date   2584 non-null   str
dtypes: int64(1), str(4)
memory usage: 101.1 KB

In [100]:

orders.order_date = pd.to_datetime(orders.order_date)

In [101]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 2584 entries, 0 to 2583
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     2584 non-null   str
 1   customer_id  2584 non-null   str
 2   product_id   2584 non-null   str
 3   quantity     2584 non-null   int64
 4   order_date   2584 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 101.1 KB

In [103]:
orders['year'] = orders.order_date.dt.year

In [105]:
orders.groupby('year')['quantity'].sum()

year
2022    2549
2023    2861
2024    2387
Name: quantity, dtype: int64